version: '3.8'

# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-sgs-frontend:
    build:
      context: .
      target: development
    depends_on:
      - redis
    image: ffc-sgs-frontend-development
    environment:
      NODE_ENV: development
    ports:
      - "3700:3700"
      - "9255:9229"
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json
  ffc-sgs-frontend-postgres:
    ports:
      - "5432:5432"

  redis:
    image: redis:4.0.14
    volumes:
      - redis_data:/data
    ports:
      - "6389:6379"

volumes:
  redis_data:
